version: 0.0
os: linux
files:
- source: /dist
  destination: /home/ec2-user/express-service/dist
- source: /config
  destination: /home/ec2-user/express-service/config
- source: /public
  destination: /home/ec2-user/express-service/public
- source: /client
  destination: /home/ec2-user/express-service/client
- source: /tests
  destination: /home/ec2-user/express-service/tests
- source: /server.js
  destination: /home/ec2-user/express-service
- source: /package.json
  destination: /home/ec2-user/express-service
- source: /node_modules
  destination: /home/ec2-user/express-service/node_modules
- source: /scripts/requirements.txt
  destination: /home/ec2-user/scripts
hooks:
  AfterInstall:
  - location: scripts/install_python3
    timeout: 300
    runas: root
  - location: scripts/codestar_remote_access
    timeout: 300
    runas: root
  - location: scripts/install_node
    timeout: 300
    runas: root
  - location: scripts/install_httpd
    timeout: 300
    runas: root
  ApplicationStart:
  - location: scripts/start_server
    timeout: 300
    runas: root
