#!/bin/bash

#isExistApp=`pgrep httpd`
#if [[ -n  $isExistApp ]]; then
#    service httpd stop        
#fi
#pkill -f node
echo "Stoping Server . . ."
service httpd stop
#https://github.com/awsdocs/aws-codedeploy-user-guide/issues/41